### PR TITLE
README: use legit markdown + tweaks

### PR DESCRIPTION
**Pull request by luzpaz**
* Remove HTML markup  
* Decrease size of headers  
* Rename some headers
* Add License  
* other misc. tweaks

Preview: https://github.com/luzpaz/AnimationFreeCAD/blob/README/README.md

### CODE REVIEW

**Comment by luzpaz** [comment]
obviously these are suggestions, feel free to pick and choose what you'd like to keep. 

Question: 
- [ ] Have you tested on MacOS?
- [ ] Have you tested on FreeCAD v0.20dev (which will be released soon since we're in a feature freeze ATM)
- [ ] Why did you choose Apache license?

**Comment by AndreasCottet** [comment]
> obviously these are suggestions, feel free to pick and choose what you'd like to keep.
> 
> Question:
> 
>     * [ ]  Have you tested on MacOS?
> 
>     * [ ]  Have you tested on FreeCAD v0.20dev (which will be released soon since we're in a feature freeze ATM)
> 
>     * [ ]  Why did you choose Apache license?


Unfortunately we were not able to test it on Mac OS as none of us have one.
This version has not been tested on FreeCAD version 0.20.
We have chosen the same license as using the PyFlow Framework because we are comfortable with these rights.

**Comment by luzpaz** [comment]
We are very close to releasing FreeCAD v0.20 stable. So it would be great if this workbench would be compatible (as best as possible) with it when we do. Theoretically, we could add this workbench to the FreeCAD addon manager under experimental. If we do, would you be open to testing v0.20 and fixing bugs from users higher probability we could find some macos testers as well)

**Comment by AndreasCottet** [comment]
Yes, we will be very proud to offer our module in experimental.
Where can we download the dev version of FreeCAD 0.20.
Will FreeCAD be able to update its modules automatically in this version?

**Comment by luzpaz** [comment]
@SHaiZen25 

https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds
snap edge/nightly: https://github.com/ppd/freecad-ppd 

The Addon Manager is a lot more intelligent in v0.20. It may be able to install all the dependencies you need (but we need to make sure those 3rd party packages are available via `pip` and are added to https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/AddonManager/ALLOWED_PYTHON_PACKAGES.txt

Best place to start a conversation is in the forum.freecad.org 

Edit: also adding Animation Workbench to [FreeCAD-addons](https://github.com/FreeCAD/FreeCAD-addons/)

**Comment by AndreasCottet** [comment]
I have just replied to you on the FreeCAD forum
https://forum.freecadweb.org/viewtopic.php?f=8&t=36299&p=588172#p588172

**Pull request merged**
